# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Body4(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'not_revision_managed': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'not_revision_managed': 'notRevisionManaged'
    }

    def __init__(self, name=None, description=None, not_revision_managed=None):  # noqa: E501
        """Body4 - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._not_revision_managed = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if not_revision_managed is not None:
            self.not_revision_managed = not_revision_managed

    @property
    def name(self):
        """Gets the name of this Body4.  # noqa: E501

        New document name  # noqa: E501

        :return: The name of this Body4.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body4.

        New document name  # noqa: E501

        :param name: The name of this Body4.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Body4.  # noqa: E501

        New document description  # noqa: E501

        :return: The description of this Body4.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Body4.

        New document description  # noqa: E501

        :param description: The description of this Body4.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def not_revision_managed(self):
        """Gets the not_revision_managed of this Body4.  # noqa: E501

        Whether document is not revision managed  # noqa: E501

        :return: The not_revision_managed of this Body4.  # noqa: E501
        :rtype: bool
        """
        return self._not_revision_managed

    @not_revision_managed.setter
    def not_revision_managed(self, not_revision_managed):
        """Sets the not_revision_managed of this Body4.

        Whether document is not revision managed  # noqa: E501

        :param not_revision_managed: The not_revision_managed of this Body4.  # noqa: E501
        :type: bool
        """

        self._not_revision_managed = not_revision_managed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body4):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
