# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.inline_response2001_thumbnail_sizes import InlineResponse2001ThumbnailSizes  # noqa: F401,E501


class InlineResponse2001Thumbnail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sizes': 'list[InlineResponse2001ThumbnailSizes]',
        'id': 'str',
        'href': 'str'
    }

    attribute_map = {
        'sizes': 'sizes',
        'id': 'id',
        'href': 'href'
    }

    def __init__(self, sizes=None, id=None, href=None):  # noqa: E501
        """InlineResponse2001Thumbnail - a model defined in Swagger"""  # noqa: E501

        self._sizes = None
        self._id = None
        self._href = None
        self.discriminator = None

        self.sizes = sizes
        self.id = id
        self.href = href

    @property
    def sizes(self):
        """Gets the sizes of this InlineResponse2001Thumbnail.  # noqa: E501

        Thumbnail sizes  # noqa: E501

        :return: The sizes of this InlineResponse2001Thumbnail.  # noqa: E501
        :rtype: list[InlineResponse2001ThumbnailSizes]
        """
        return self._sizes

    @sizes.setter
    def sizes(self, sizes):
        """Sets the sizes of this InlineResponse2001Thumbnail.

        Thumbnail sizes  # noqa: E501

        :param sizes: The sizes of this InlineResponse2001Thumbnail.  # noqa: E501
        :type: list[InlineResponse2001ThumbnailSizes]
        """
        if sizes is None:
            raise ValueError("Invalid value for `sizes`, must not be `None`")  # noqa: E501

        self._sizes = sizes

    @property
    def id(self):
        """Gets the id of this InlineResponse2001Thumbnail.  # noqa: E501

        Thumbnail id  # noqa: E501

        :return: The id of this InlineResponse2001Thumbnail.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2001Thumbnail.

        Thumbnail id  # noqa: E501

        :param id: The id of this InlineResponse2001Thumbnail.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def href(self):
        """Gets the href of this InlineResponse2001Thumbnail.  # noqa: E501

        Thumbnail URL  # noqa: E501

        :return: The href of this InlineResponse2001Thumbnail.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this InlineResponse2001Thumbnail.

        Thumbnail URL  # noqa: E501

        :param href: The href of this InlineResponse2001Thumbnail.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001Thumbnail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
