# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.inline_response200_created_by import InlineResponse200CreatedBy  # noqa: F401,E501
from swagger_client.models.inline_response200_default_workspace import InlineResponse200DefaultWorkspace  # noqa: F401,E501
from swagger_client.models.inline_response200_modified_by import InlineResponse200ModifiedBy  # noqa: F401,E501
from swagger_client.models.inline_response200_owner import InlineResponse200Owner  # noqa: F401,E501
from swagger_client.models.inline_response200_thumbnail import InlineResponse200Thumbnail  # noqa: F401,E501


class InlineResponse200Items(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public': 'bool',
        'owner': 'InlineResponse200Owner',
        'permission': 'str',
        'trashed_at': 'datetime',
        'trash': 'bool',
        'starred': 'str',
        'active': 'bool',
        'created_at': 'datetime',
        'thumbnail': 'InlineResponse200Thumbnail',
        'created_by': 'InlineResponse200CreatedBy',
        'modified_at': 'datetime',
        'modified_by': 'InlineResponse200ModifiedBy',
        'default_workspace': 'InlineResponse200DefaultWorkspace',
        'tags': 'list[str]',
        'size_bytes': 'float',
        'can_unshare': 'bool',
        'name': 'str',
        'id': 'str',
        'href': 'str',
        'total_workspaces_updating': 'float',
        'total_workspaces_scheduled_for_update': 'float'
    }

    attribute_map = {
        'public': 'public',
        'owner': 'owner',
        'permission': 'permission',
        'trashed_at': 'trashedAt',
        'trash': 'trash',
        'starred': 'starred',
        'active': 'active',
        'created_at': 'createdAt',
        'thumbnail': 'thumbnail',
        'created_by': 'createdBy',
        'modified_at': 'modifiedAt',
        'modified_by': 'modifiedBy',
        'default_workspace': 'defaultWorkspace',
        'tags': 'tags',
        'size_bytes': 'sizeBytes',
        'can_unshare': 'canUnshare',
        'name': 'name',
        'id': 'id',
        'href': 'href',
        'total_workspaces_updating': 'totalWorkspacesUpdating',
        'total_workspaces_scheduled_for_update': 'totalWorkspacesScheduledForUpdate'
    }

    def __init__(self, public=None, owner=None, permission=None, trashed_at=None, trash=None, starred=None, active=None, created_at=None, thumbnail=None, created_by=None, modified_at=None, modified_by=None, default_workspace=None, tags=None, size_bytes=None, can_unshare=None, name=None, id=None, href=None, total_workspaces_updating=None, total_workspaces_scheduled_for_update=None):  # noqa: E501
        """InlineResponse200Items - a model defined in Swagger"""  # noqa: E501

        self._public = None
        self._owner = None
        self._permission = None
        self._trashed_at = None
        self._trash = None
        self._starred = None
        self._active = None
        self._created_at = None
        self._thumbnail = None
        self._created_by = None
        self._modified_at = None
        self._modified_by = None
        self._default_workspace = None
        self._tags = None
        self._size_bytes = None
        self._can_unshare = None
        self._name = None
        self._id = None
        self._href = None
        self._total_workspaces_updating = None
        self._total_workspaces_scheduled_for_update = None
        self.discriminator = None

        self.public = public
        self.owner = owner
        self.permission = permission
        self.trashed_at = trashed_at
        self.trash = trash
        self.starred = starred
        self.active = active
        self.created_at = created_at
        self.thumbnail = thumbnail
        self.created_by = created_by
        self.modified_at = modified_at
        self.modified_by = modified_by
        self.default_workspace = default_workspace
        self.tags = tags
        self.size_bytes = size_bytes
        self.can_unshare = can_unshare
        self.name = name
        self.id = id
        self.href = href
        self.total_workspaces_updating = total_workspaces_updating
        self.total_workspaces_scheduled_for_update = total_workspaces_scheduled_for_update

    @property
    def public(self):
        """Gets the public of this InlineResponse200Items.  # noqa: E501

        Whether document is public  # noqa: E501

        :return: The public of this InlineResponse200Items.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this InlineResponse200Items.

        Whether document is public  # noqa: E501

        :param public: The public of this InlineResponse200Items.  # noqa: E501
        :type: bool
        """
        if public is None:
            raise ValueError("Invalid value for `public`, must not be `None`")  # noqa: E501

        self._public = public

    @property
    def owner(self):
        """Gets the owner of this InlineResponse200Items.  # noqa: E501


        :return: The owner of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200Owner
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this InlineResponse200Items.


        :param owner: The owner of this InlineResponse200Items.  # noqa: E501
        :type: InlineResponse200Owner
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501

        self._owner = owner

    @property
    def permission(self):
        """Gets the permission of this InlineResponse200Items.  # noqa: E501

        Onshape internal use  # noqa: E501

        :return: The permission of this InlineResponse200Items.  # noqa: E501
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this InlineResponse200Items.

        Onshape internal use  # noqa: E501

        :param permission: The permission of this InlineResponse200Items.  # noqa: E501
        :type: str
        """
        if permission is None:
            raise ValueError("Invalid value for `permission`, must not be `None`")  # noqa: E501

        self._permission = permission

    @property
    def trashed_at(self):
        """Gets the trashed_at of this InlineResponse200Items.  # noqa: E501

        When document has been trashed  # noqa: E501

        :return: The trashed_at of this InlineResponse200Items.  # noqa: E501
        :rtype: datetime
        """
        return self._trashed_at

    @trashed_at.setter
    def trashed_at(self, trashed_at):
        """Sets the trashed_at of this InlineResponse200Items.

        When document has been trashed  # noqa: E501

        :param trashed_at: The trashed_at of this InlineResponse200Items.  # noqa: E501
        :type: datetime
        """
        if trashed_at is None:
            raise ValueError("Invalid value for `trashed_at`, must not be `None`")  # noqa: E501

        self._trashed_at = trashed_at

    @property
    def trash(self):
        """Gets the trash of this InlineResponse200Items.  # noqa: E501

        Whether document has been trashed  # noqa: E501

        :return: The trash of this InlineResponse200Items.  # noqa: E501
        :rtype: bool
        """
        return self._trash

    @trash.setter
    def trash(self, trash):
        """Sets the trash of this InlineResponse200Items.

        Whether document has been trashed  # noqa: E501

        :param trash: The trash of this InlineResponse200Items.  # noqa: E501
        :type: bool
        """
        if trash is None:
            raise ValueError("Invalid value for `trash`, must not be `None`")  # noqa: E501

        self._trash = trash

    @property
    def starred(self):
        """Gets the starred of this InlineResponse200Items.  # noqa: E501

        Whether document has been starred  # noqa: E501

        :return: The starred of this InlineResponse200Items.  # noqa: E501
        :rtype: str
        """
        return self._starred

    @starred.setter
    def starred(self, starred):
        """Sets the starred of this InlineResponse200Items.

        Whether document has been starred  # noqa: E501

        :param starred: The starred of this InlineResponse200Items.  # noqa: E501
        :type: str
        """
        if starred is None:
            raise ValueError("Invalid value for `starred`, must not be `None`")  # noqa: E501

        self._starred = starred

    @property
    def active(self):
        """Gets the active of this InlineResponse200Items.  # noqa: E501

        Whether a shared document is active  # noqa: E501

        :return: The active of this InlineResponse200Items.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this InlineResponse200Items.

        Whether a shared document is active  # noqa: E501

        :param active: The active of this InlineResponse200Items.  # noqa: E501
        :type: bool
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def created_at(self):
        """Gets the created_at of this InlineResponse200Items.  # noqa: E501

        Creation date  # noqa: E501

        :return: The created_at of this InlineResponse200Items.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this InlineResponse200Items.

        Creation date  # noqa: E501

        :param created_at: The created_at of this InlineResponse200Items.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def thumbnail(self):
        """Gets the thumbnail of this InlineResponse200Items.  # noqa: E501


        :return: The thumbnail of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200Thumbnail
        """
        return self._thumbnail

    @thumbnail.setter
    def thumbnail(self, thumbnail):
        """Sets the thumbnail of this InlineResponse200Items.


        :param thumbnail: The thumbnail of this InlineResponse200Items.  # noqa: E501
        :type: InlineResponse200Thumbnail
        """
        if thumbnail is None:
            raise ValueError("Invalid value for `thumbnail`, must not be `None`")  # noqa: E501

        self._thumbnail = thumbnail

    @property
    def created_by(self):
        """Gets the created_by of this InlineResponse200Items.  # noqa: E501


        :return: The created_by of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200CreatedBy
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this InlineResponse200Items.


        :param created_by: The created_by of this InlineResponse200Items.  # noqa: E501
        :type: InlineResponse200CreatedBy
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def modified_at(self):
        """Gets the modified_at of this InlineResponse200Items.  # noqa: E501

        Date of last modification  # noqa: E501

        :return: The modified_at of this InlineResponse200Items.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this InlineResponse200Items.

        Date of last modification  # noqa: E501

        :param modified_at: The modified_at of this InlineResponse200Items.  # noqa: E501
        :type: datetime
        """
        if modified_at is None:
            raise ValueError("Invalid value for `modified_at`, must not be `None`")  # noqa: E501

        self._modified_at = modified_at

    @property
    def modified_by(self):
        """Gets the modified_by of this InlineResponse200Items.  # noqa: E501


        :return: The modified_by of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200ModifiedBy
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this InlineResponse200Items.


        :param modified_by: The modified_by of this InlineResponse200Items.  # noqa: E501
        :type: InlineResponse200ModifiedBy
        """
        if modified_by is None:
            raise ValueError("Invalid value for `modified_by`, must not be `None`")  # noqa: E501

        self._modified_by = modified_by

    @property
    def default_workspace(self):
        """Gets the default_workspace of this InlineResponse200Items.  # noqa: E501


        :return: The default_workspace of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200DefaultWorkspace
        """
        return self._default_workspace

    @default_workspace.setter
    def default_workspace(self, default_workspace):
        """Sets the default_workspace of this InlineResponse200Items.


        :param default_workspace: The default_workspace of this InlineResponse200Items.  # noqa: E501
        :type: InlineResponse200DefaultWorkspace
        """
        if default_workspace is None:
            raise ValueError("Invalid value for `default_workspace`, must not be `None`")  # noqa: E501

        self._default_workspace = default_workspace

    @property
    def tags(self):
        """Gets the tags of this InlineResponse200Items.  # noqa: E501

        Reserved for future use  # noqa: E501

        :return: The tags of this InlineResponse200Items.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this InlineResponse200Items.

        Reserved for future use  # noqa: E501

        :param tags: The tags of this InlineResponse200Items.  # noqa: E501
        :type: list[str]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags

    @property
    def size_bytes(self):
        """Gets the size_bytes of this InlineResponse200Items.  # noqa: E501

        Size of document in bytes  # noqa: E501

        :return: The size_bytes of this InlineResponse200Items.  # noqa: E501
        :rtype: float
        """
        return self._size_bytes

    @size_bytes.setter
    def size_bytes(self, size_bytes):
        """Sets the size_bytes of this InlineResponse200Items.

        Size of document in bytes  # noqa: E501

        :param size_bytes: The size_bytes of this InlineResponse200Items.  # noqa: E501
        :type: float
        """
        if size_bytes is None:
            raise ValueError("Invalid value for `size_bytes`, must not be `None`")  # noqa: E501

        self._size_bytes = size_bytes

    @property
    def can_unshare(self):
        """Gets the can_unshare of this InlineResponse200Items.  # noqa: E501

        Whether document can be unshared  # noqa: E501

        :return: The can_unshare of this InlineResponse200Items.  # noqa: E501
        :rtype: bool
        """
        return self._can_unshare

    @can_unshare.setter
    def can_unshare(self, can_unshare):
        """Sets the can_unshare of this InlineResponse200Items.

        Whether document can be unshared  # noqa: E501

        :param can_unshare: The can_unshare of this InlineResponse200Items.  # noqa: E501
        :type: bool
        """
        if can_unshare is None:
            raise ValueError("Invalid value for `can_unshare`, must not be `None`")  # noqa: E501

        self._can_unshare = can_unshare

    @property
    def name(self):
        """Gets the name of this InlineResponse200Items.  # noqa: E501

        Name of document  # noqa: E501

        :return: The name of this InlineResponse200Items.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse200Items.

        Name of document  # noqa: E501

        :param name: The name of this InlineResponse200Items.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def id(self):
        """Gets the id of this InlineResponse200Items.  # noqa: E501

        Document ID  # noqa: E501

        :return: The id of this InlineResponse200Items.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse200Items.

        Document ID  # noqa: E501

        :param id: The id of this InlineResponse200Items.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def href(self):
        """Gets the href of this InlineResponse200Items.  # noqa: E501

        Document URL  # noqa: E501

        :return: The href of this InlineResponse200Items.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this InlineResponse200Items.

        Document URL  # noqa: E501

        :param href: The href of this InlineResponse200Items.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def total_workspaces_updating(self):
        """Gets the total_workspaces_updating of this InlineResponse200Items.  # noqa: E501

        Number of workspaces that are updating  # noqa: E501

        :return: The total_workspaces_updating of this InlineResponse200Items.  # noqa: E501
        :rtype: float
        """
        return self._total_workspaces_updating

    @total_workspaces_updating.setter
    def total_workspaces_updating(self, total_workspaces_updating):
        """Sets the total_workspaces_updating of this InlineResponse200Items.

        Number of workspaces that are updating  # noqa: E501

        :param total_workspaces_updating: The total_workspaces_updating of this InlineResponse200Items.  # noqa: E501
        :type: float
        """
        if total_workspaces_updating is None:
            raise ValueError("Invalid value for `total_workspaces_updating`, must not be `None`")  # noqa: E501

        self._total_workspaces_updating = total_workspaces_updating

    @property
    def total_workspaces_scheduled_for_update(self):
        """Gets the total_workspaces_scheduled_for_update of this InlineResponse200Items.  # noqa: E501

        Number of workspaces that are scheduled             for updating  # noqa: E501

        :return: The total_workspaces_scheduled_for_update of this InlineResponse200Items.  # noqa: E501
        :rtype: float
        """
        return self._total_workspaces_scheduled_for_update

    @total_workspaces_scheduled_for_update.setter
    def total_workspaces_scheduled_for_update(self, total_workspaces_scheduled_for_update):
        """Sets the total_workspaces_scheduled_for_update of this InlineResponse200Items.

        Number of workspaces that are scheduled             for updating  # noqa: E501

        :param total_workspaces_scheduled_for_update: The total_workspaces_scheduled_for_update of this InlineResponse200Items.  # noqa: E501
        :type: float
        """
        if total_workspaces_scheduled_for_update is None:
            raise ValueError("Invalid value for `total_workspaces_scheduled_for_update`, must not be `None`")  # noqa: E501

        self._total_workspaces_scheduled_for_update = total_workspaces_scheduled_for_update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200Items):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
