# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body_19 import Body19  # noqa: E501
from swagger_client.rest import ApiException


class TestBody19(unittest.TestCase):
    """Body19 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody19(self):
        """Test Body19"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body_19.Body19()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
