# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_23_bom_table_bom_source_element import InlineResponse20023BomTableBomSourceElement  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20023BomTableBomSourceElement(unittest.TestCase):
    """InlineResponse20023BomTableBomSourceElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023BomTableBomSourceElement(self):
        """Test InlineResponse20023BomTableBomSourceElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_23_bom_table_bom_source_element.InlineResponse20023BomTableBomSourceElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
