# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_purchase_new_accounts(self):
        """Test case for cancel_purchase_new_accounts

        Cancel Recurring Subscription  # noqa: E501
        """
        pass

    def test_consume_purchase_accounts(self):
        """Test case for consume_purchase_accounts

        Mark Purchase Consumed For User  # noqa: E501
        """
        pass

    def test_get_plan_purchases_accounts(self):
        """Test case for get_plan_purchases_accounts

        Get Plan Purchases  # noqa: E501
        """
        pass

    def test_get_purchases_accounts(self):
        """Test case for get_purchases_accounts

        Get User's Appstore Purchases  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
