# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.translations_api import TranslationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTranslationsApi(unittest.TestCase):
    """TranslationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.translations_api.TranslationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_translation_translations(self):
        """Test case for create_translation_translations

        Create translation from upload  # noqa: E501
        """
        pass

    def test_delete_translation_translations(self):
        """Test case for delete_translation_translations

        Delete Translation Status entry  # noqa: E501
        """
        pass

    def test_get_translation_translations(self):
        """Test case for get_translation_translations

        Get Translation Status  # noqa: E501
        """
        pass

    def test_get_translations_translations(self):
        """Test case for get_translations_translations

        Get Translation Status for a document  # noqa: E501
        """
        pass

    def test_get_translator_formats_translations(self):
        """Test case for get_translator_formats_translations

        Get Translation Formats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
