# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.assembliesddidwwideeidtransformedinstances_instances import AssembliesddidwwideeidtransformedinstancesInstances  # noqa: E501
from swagger_client.rest import ApiException


class TestAssembliesddidwwideeidtransformedinstancesInstances(unittest.TestCase):
    """AssembliesddidwwideeidtransformedinstancesInstances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssembliesddidwwideeidtransformedinstancesInstances(self):
        """Test AssembliesddidwwideeidtransformedinstancesInstances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.assembliesddidwwideeidtransformedinstances_instances.AssembliesddidwwideeidtransformedinstancesInstances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
