# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_40_workspaces import InlineResponse20040Workspaces  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20040Workspaces(unittest.TestCase):
    """InlineResponse20040Workspaces unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20040Workspaces(self):
        """Test InlineResponse20040Workspaces"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_40_workspaces.InlineResponse20040Workspaces()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
