# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.metadata_api import MetadataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.metadata_api.MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_metadata_metadata(self):
        """Test case for get_metadata_metadata

        Get Workspace / Version Metadata  # noqa: E501
        """
        pass

    def test_get_metadata_property_metadata(self):
        """Test case for get_metadata_property_metadata

        Get metadata property  # noqa: E501
        """
        pass

    def test_get_metadata_schema_by_id_metadata(self):
        """Test case for get_metadata_schema_by_id_metadata

        Get metadata schema by ID  # noqa: E501
        """
        pass

    def test_get_metadata_schema_metadata(self):
        """Test case for get_metadata_schema_metadata

        Get metadata schema by owner  # noqa: E501
        """
        pass

    def test_get_metadata_schema_properties_metadata(self):
        """Test case for get_metadata_schema_properties_metadata

        Get metadata properties  # noqa: E501
        """
        pass

    def test_get_part_list_metadata_metadata(self):
        """Test case for get_part_list_metadata_metadata

        Get Parts Metadata  # noqa: E501
        """
        pass

    def test_get_part_metadata_metadata(self):
        """Test case for get_part_metadata_metadata

        Get Part Metadata  # noqa: E501
        """
        pass

    def test_get_standard_content_metadata_metadata(self):
        """Test case for get_standard_content_metadata_metadata

        Get Standard Content Part Metadata  # noqa: E501
        """
        pass

    def test_update_metadata_metadata(self):
        """Test case for update_metadata_metadata

        Update Metadata  # noqa: E501
        """
        pass

    def test_update_standard_content_metadata_metadata(self):
        """Test case for update_standard_content_metadata_metadata

        Update Standard Content Part Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
