# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body_40 import Body40  # noqa: E501
from swagger_client.rest import ApiException


class TestBody40(unittest.TestCase):
    """Body40 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody40(self):
        """Test Body40"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body_40.Body40()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
