# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.drawings_api import DrawingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDrawingsApi(unittest.TestCase):
    """DrawingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.drawings_api.DrawingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_translation_drawings(self):
        """Test case for create_translation_drawings

        Create Drawing Translation  # noqa: E501
        """
        pass

    def test_get_translation_formats_drawings(self):
        """Test case for get_translation_formats_drawings

        Get Translation Formats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
