# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_75_geom_entities import InlineResponse20075GeomEntities  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20075GeomEntities(unittest.TestCase):
    """InlineResponse20075GeomEntities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20075GeomEntities(self):
        """Test InlineResponse20075GeomEntities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_75_geom_entities.InlineResponse20075GeomEntities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
