# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_66_box import InlineResponse20066Box  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20066Box(unittest.TestCase):
    """InlineResponse20066Box unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20066Box(self):
        """Test InlineResponse20066Box"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_66_box.InlineResponse20066Box()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
