# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body_32 import Body32  # noqa: E501
from swagger_client.rest import ApiException


class TestBody32(unittest.TestCase):
    """Body32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody32(self):
        """Test Body32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body_32.Body32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
