# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_101_items import InlineResponse200101Items  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200101Items(unittest.TestCase):
    """InlineResponse200101Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200101Items(self):
        """Test InlineResponse200101Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_101_items.InlineResponse200101Items()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
