# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_67_changes import InlineResponse20067Changes  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20067Changes(unittest.TestCase):
    """InlineResponse20067Changes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20067Changes(self):
        """Test InlineResponse20067Changes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_67_changes.InlineResponse20067Changes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
