# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_documents_documents_modified_by import GetDocumentsDocumentsModifiedBy  # noqa: E501
from swagger_client.rest import ApiException


class TestGetDocumentsDocumentsModifiedBy(unittest.TestCase):
    """GetDocumentsDocumentsModifiedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocumentsDocumentsModifiedBy(self):
        """Test GetDocumentsDocumentsModifiedBy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_documents_documents_modified_by.GetDocumentsDocumentsModifiedBy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
