# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_98_sizes import InlineResponse20098Sizes  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20098Sizes(unittest.TestCase):
    """InlineResponse20098Sizes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20098Sizes(self):
        """Test InlineResponse20098Sizes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_98_sizes.InlineResponse20098Sizes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
