# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_103_view_manipulation_mouse_key_mapping_zoom2_d_mapping import InlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping(unittest.TestCase):
    """InlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping(self):
        """Test InlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_103_view_manipulation_mouse_key_mapping_zoom2_d_mapping.InlineResponse200103ViewManipulationMouseKeyMappingZoom2DMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
