# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.thumbnails_api import ThumbnailsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestThumbnailsApi(unittest.TestCase):
    """ThumbnailsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.thumbnails_api.ThumbnailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_application_thumbnails_thumbnails(self):
        """Test case for delete_application_thumbnails_thumbnails

        Delete Application Element Thumbnail  # noqa: E501
        """
        pass

    def test_get_configured_element_thumbnail_with_size_thumbnails(self):
        """Test case for get_configured_element_thumbnail_with_size_thumbnails

        Get Configured Element Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_document_thumbnail_thumbnails(self):
        """Test case for get_document_thumbnail_thumbnails

        Get Document Thumbnail Info  # noqa: E501
        """
        pass

    def test_get_document_thumbnail_with_size_thumbnails(self):
        """Test case for get_document_thumbnail_with_size_thumbnails

        Get Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_element_thumbnail_thumbnails(self):
        """Test case for get_element_thumbnail_thumbnails

        Get Element Thumbnail Info  # noqa: E501
        """
        pass

    def test_get_element_thumbnail_with_size_thumbnails(self):
        """Test case for get_element_thumbnail_with_size_thumbnails

        Get Element Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_thumbnail_for_document_and_version_thumbnails(self):
        """Test case for get_thumbnail_for_document_and_version_thumbnails

        Get Thumbnail Info For Document Version  # noqa: E501
        """
        pass

    def test_get_thumbnail_for_document_thumbnails(self):
        """Test case for get_thumbnail_for_document_thumbnails

        Get Default Workspace Thumbnail Info  # noqa: E501
        """
        pass

    def test_set_application_element_thumbnail_thumbnails(self):
        """Test case for set_application_element_thumbnail_thumbnails

        Set Application Element Thumbnail  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
