# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.documents_api import DocumentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.documents_api.DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_workspace_documents(self):
        """Test case for copy_workspace_documents

        Copy Workspace  # noqa: E501
        """
        pass

    def test_create_document_documents(self):
        """Test case for create_document_documents

        Create Document  # noqa: E501
        """
        pass

    def test_create_version_documents(self):
        """Test case for create_version_documents

        Create Version  # noqa: E501
        """
        pass

    def test_create_workspace_documents(self):
        """Test case for create_workspace_documents

        Create Workspace  # noqa: E501
        """
        pass

    def test_delete_document_documents(self):
        """Test case for delete_document_documents

        Delete Document  # noqa: E501
        """
        pass

    def test_delete_workspace_documents(self):
        """Test case for delete_workspace_documents

        Delete Workspace  # noqa: E501
        """
        pass

    def test_download_external_data_documents(self):
        """Test case for download_external_data_documents

        Download External Data  # noqa: E501
        """
        pass

    def test_export_element_documents(self):
        """Test case for export_element_documents

        Export Element (307)  # noqa: E501
        """
        pass

    def test_export_element_post_json_documents(self):
        """Test case for export_element_post_json_documents

        Export Element (URI)  # noqa: E501
        """
        pass

    def test_get_acl_documents(self):
        """Test case for get_acl_documents

        Get Access Control List  # noqa: E501
        """
        pass

    def test_get_current_microversion_documents(self):
        """Test case for get_current_microversion_documents

        Get Current Document Microversion  # noqa: E501
        """
        pass

    def test_get_document_documents(self):
        """Test case for get_document_documents

        Get Document  # noqa: E501
        """
        pass

    def test_get_document_permission_set_documents(self):
        """Test case for get_document_permission_set_documents

        Get Document Permissions  # noqa: E501
        """
        pass

    def test_get_documents_documents(self):
        """Test case for get_documents_documents

        Get Documents  # noqa: E501
        """
        pass

    def test_get_element_list_documents(self):
        """Test case for get_element_list_documents

        Element List  # noqa: E501
        """
        pass

    def test_get_insertables_documents(self):
        """Test case for get_insertables_documents

        Insertable List for Document Version.  # noqa: E501
        """
        pass

    def test_get_version_documents(self):
        """Test case for get_version_documents

        Get Version  # noqa: E501
        """
        pass

    def test_get_versions_documents(self):
        """Test case for get_versions_documents

        Get Versions  # noqa: E501
        """
        pass

    def test_get_workspaces_documents(self):
        """Test case for get_workspaces_documents

        Get Workspaces  # noqa: E501
        """
        pass

    def test_move_elements_to_document_documents(self):
        """Test case for move_elements_to_document_documents

        Move Elements  # noqa: E501
        """
        pass

    def test_share_document_documents(self):
        """Test case for share_document_documents

        Share Document  # noqa: E501
        """
        pass

    def test_un_share_documents(self):
        """Test case for un_share_documents

        Unshare Document  # noqa: E501
        """
        pass

    def test_update_document_attributes_documents(self):
        """Test case for update_document_attributes_documents

        Update Document Attributes.  # noqa: E501
        """
        pass

    def test_update_external_references_to_latest_documents_documents(self):
        """Test case for update_external_references_to_latest_documents_documents

        Update External References to Latest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
