# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metadatastandardcontentddidvvideeidcu_charoidppid_properties import MetadatastandardcontentddidvvideeidcuCharoidppidProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadatastandardcontentddidvvideeidcuCharoidppidProperties(unittest.TestCase):
    """MetadatastandardcontentddidvvideeidcuCharoidppidProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadatastandardcontentddidvvideeidcuCharoidppidProperties(self):
        """Test MetadatastandardcontentddidvvideeidcuCharoidppidProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metadatastandardcontentddidvvideeidcu_charoidppid_properties.MetadatastandardcontentddidvvideeidcuCharoidppidProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
