# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.feature_studios_api import FeatureStudiosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeatureStudiosApi(unittest.TestCase):
    """FeatureStudiosApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.feature_studios_api.FeatureStudiosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_feature_studio_feature_studios(self):
        """Test case for create_feature_studio_feature_studios

        Create Feature Studio  # noqa: E501
        """
        pass

    def test_get_feature_studio_contents_feature_studios(self):
        """Test case for get_feature_studio_contents_feature_studios

        Get Feature Studio Contents  # noqa: E501
        """
        pass

    def test_get_feature_studio_specs_feature_studios(self):
        """Test case for get_feature_studio_specs_feature_studios

        Get Feature Studio Specs  # noqa: E501
        """
        pass

    def test_update_feature_studio_contents_feature_studios(self):
        """Test case for update_feature_studio_contents_feature_studios

        Update Feature Studio contents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
