# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assemblies_api import AssembliesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssembliesApi(unittest.TestCase):
    """AssembliesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assemblies_api.AssembliesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_feature_assemblies(self):
        """Test case for add_feature_assemblies

        Add Feature  # noqa: E501
        """
        pass

    def test_create_assembly_assemblies(self):
        """Test case for create_assembly_assemblies

        Create Assembly  # noqa: E501
        """
        pass

    def test_create_instance_assemblies(self):
        """Test case for create_instance_assemblies

        Create assembly instance  # noqa: E501
        """
        pass

    def test_create_translation_assemblies(self):
        """Test case for create_translation_assemblies

        Create Assembly translation  # noqa: E501
        """
        pass

    def test_delete_feature_assemblies(self):
        """Test case for delete_feature_assemblies

        Delete Feature  # noqa: E501
        """
        pass

    def test_delete_instance_assemblies(self):
        """Test case for delete_instance_assemblies

        Delete assembly instance  # noqa: E501
        """
        pass

    def test_get_assembly_definition_assemblies(self):
        """Test case for get_assembly_definition_assemblies

        Assembly Definition  # noqa: E501
        """
        pass

    def test_get_bill_of_materials_assemblies(self):
        """Test case for get_bill_of_materials_assemblies

        Get Bill of Materials  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_assemblies(self):
        """Test case for get_bounding_boxes_assemblies

        Bounding Boxes  # noqa: E501
        """
        pass

    def test_get_feature_specs_assemblies(self):
        """Test case for get_feature_specs_assemblies

        Get Feature Specs  # noqa: E501
        """
        pass

    def test_get_features_assemblies(self):
        """Test case for get_features_assemblies

        Get Feature List  # noqa: E501
        """
        pass

    def test_get_named_views_assemblies(self):
        """Test case for get_named_views_assemblies

        Get Named Views  # noqa: E501
        """
        pass

    def test_get_or_create_bill_of_materials_element_assemblies(self):
        """Test case for get_or_create_bill_of_materials_element_assemblies

        Get or Create Bill of Materials Element  # noqa: E501
        """
        pass

    def test_get_shaded_views_assemblies(self):
        """Test case for get_shaded_views_assemblies

        Shaded Views  # noqa: E501
        """
        pass

    def test_get_translation_formats_assemblies(self):
        """Test case for get_translation_formats_assemblies

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_insert_transformed_instances_assemblies(self):
        """Test case for insert_transformed_instances_assemblies

        Create and transform assembly instances  # noqa: E501
        """
        pass

    def test_transform_occurrences_assemblies(self):
        """Test case for transform_occurrences_assemblies

        Transform assembly occurrences  # noqa: E501
        """
        pass

    def test_update_feature_assemblies(self):
        """Test case for update_feature_assemblies

        Update Feature  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
