# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.x_public_api import XPublicApi  # noqa: E501
from swagger_client.rest import ApiException


class TestXPublicApi(unittest.TestCase):
    """XPublicApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.x_public_api.XPublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_feature_assemblies(self):
        """Test case for add_feature_assemblies

        Add Feature  # noqa: E501
        """
        pass

    def test_add_feature_part_studios(self):
        """Test case for add_feature_part_studios

        Add Feature  # noqa: E501
        """
        pass

    def test_batch_update_part_metadata_parts(self):
        """Test case for batch_update_part_metadata_parts

        Update Part metadata  # noqa: E501
        """
        pass

    def test_cancel_purchase_new_accounts(self):
        """Test case for cancel_purchase_new_accounts

        Cancel Recurring Subscription  # noqa: E501
        """
        pass

    def test_commit_transaction_app_elements(self):
        """Test case for commit_transaction_app_elements

        Commit Transaction  # noqa: E501
        """
        pass

    def test_compare_part_studio_part_studios(self):
        """Test case for compare_part_studio_part_studios

        Compare Part Studio  # noqa: E501
        """
        pass

    def test_consume_purchase_accounts(self):
        """Test case for consume_purchase_accounts

        Mark Purchase Consumed For User  # noqa: E501
        """
        pass

    def test_copy_workspace_documents(self):
        """Test case for copy_workspace_documents

        Copy Workspace  # noqa: E501
        """
        pass

    def test_create_assembly_assemblies(self):
        """Test case for create_assembly_assemblies

        Create Assembly  # noqa: E501
        """
        pass

    def test_create_document_documents(self):
        """Test case for create_document_documents

        Create Document  # noqa: E501
        """
        pass

    def test_create_element_app_elements(self):
        """Test case for create_element_app_elements

        Create Element  # noqa: E501
        """
        pass

    def test_create_feature_studio_feature_studios(self):
        """Test case for create_feature_studio_feature_studios

        Create Feature Studio  # noqa: E501
        """
        pass

    def test_create_instance_assemblies(self):
        """Test case for create_instance_assemblies

        Create assembly instance  # noqa: E501
        """
        pass

    def test_create_obsoletion_package_release_management(self):
        """Test case for create_obsoletion_package_release_management

        Create obsoletion package  # noqa: E501
        """
        pass

    def test_create_part_studio_part_studios(self):
        """Test case for create_part_studio_part_studios

        Create Part Studio  # noqa: E501
        """
        pass

    def test_create_reference_app_elements(self):
        """Test case for create_reference_app_elements

        Create Reference  # noqa: E501
        """
        pass

    def test_create_release_package_release_management(self):
        """Test case for create_release_package_release_management

        Create release package  # noqa: E501
        """
        pass

    def test_create_translation_assemblies(self):
        """Test case for create_translation_assemblies

        Create Assembly translation  # noqa: E501
        """
        pass

    def test_create_translation_blob_elements(self):
        """Test case for create_translation_blob_elements

        Create Translation  # noqa: E501
        """
        pass

    def test_create_translation_drawings(self):
        """Test case for create_translation_drawings

        Create Drawing Translation  # noqa: E501
        """
        pass

    def test_create_translation_part_studios(self):
        """Test case for create_translation_part_studios

        Create Part Studio translation  # noqa: E501
        """
        pass

    def test_create_translation_translations(self):
        """Test case for create_translation_translations

        Create translation from upload  # noqa: E501
        """
        pass

    def test_create_version_documents(self):
        """Test case for create_version_documents

        Create Version  # noqa: E501
        """
        pass

    def test_create_webhook_webhooks(self):
        """Test case for create_webhook_webhooks

        Create Webhook  # noqa: E501
        """
        pass

    def test_create_workspace_documents(self):
        """Test case for create_workspace_documents

        Create Workspace  # noqa: E501
        """
        pass

    def test_decode_configuration_string_elements(self):
        """Test case for decode_configuration_string_elements

        Decode Configuration String  # noqa: E501
        """
        pass

    def test_delete_app_settings_applications(self):
        """Test case for delete_app_settings_applications

        Delete Application Settings  # noqa: E501
        """
        pass

    def test_delete_application_thumbnails_thumbnails(self):
        """Test case for delete_application_thumbnails_thumbnails

        Delete Application Element Thumbnail  # noqa: E501
        """
        pass

    def test_delete_content_app_elements(self):
        """Test case for delete_content_app_elements

        Delete a Sub-element  # noqa: E501
        """
        pass

    def test_delete_document_documents(self):
        """Test case for delete_document_documents

        Delete Document  # noqa: E501
        """
        pass

    def test_delete_element_elements(self):
        """Test case for delete_element_elements

        Delete Element  # noqa: E501
        """
        pass

    def test_delete_feature_assemblies(self):
        """Test case for delete_feature_assemblies

        Delete Feature  # noqa: E501
        """
        pass

    def test_delete_feature_part_studios(self):
        """Test case for delete_feature_part_studios

        Delete Feature  # noqa: E501
        """
        pass

    def test_delete_instance_assemblies(self):
        """Test case for delete_instance_assemblies

        Delete assembly instance  # noqa: E501
        """
        pass

    def test_delete_reference_app_elements(self):
        """Test case for delete_reference_app_elements

        Delete Reference  # noqa: E501
        """
        pass

    def test_delete_translation_translations(self):
        """Test case for delete_translation_translations

        Delete Translation Status entry  # noqa: E501
        """
        pass

    def test_delete_workspace_documents(self):
        """Test case for delete_workspace_documents

        Delete Workspace  # noqa: E501
        """
        pass

    def test_download_external_data_documents(self):
        """Test case for download_external_data_documents

        Download External Data  # noqa: E501
        """
        pass

    def test_download_file_from_element_blob_elements(self):
        """Test case for download_file_from_element_blob_elements

        Download File From Blob Element  # noqa: E501
        """
        pass

    def test_encode_configuration_elements(self):
        """Test case for encode_configuration_elements

        Encode Configuration  # noqa: E501
        """
        pass

    def test_eval_feature_script_part_studios(self):
        """Test case for eval_feature_script_part_studios

        Evaluate FeatureScript  # noqa: E501
        """
        pass

    def test_export_element_documents(self):
        """Test case for export_element_documents

        Export Element (307)  # noqa: E501
        """
        pass

    def test_export_element_post_json_documents(self):
        """Test case for export_element_post_json_documents

        Export Element (URI)  # noqa: E501
        """
        pass

    def test_export_parasolid_part_studios(self):
        """Test case for export_parasolid_part_studios

        Export Part Studio to Parasolid  # noqa: E501
        """
        pass

    def test_export_parasolid_parts(self):
        """Test case for export_parasolid_parts

        Export Part to Parasolid  # noqa: E501
        """
        pass

    def test_export_stl_part_studios(self):
        """Test case for export_stl_part_studios

        Export Part Studio to STL  # noqa: E501
        """
        pass

    def test_export_stl_parts(self):
        """Test case for export_stl_parts

        Export Part to STL  # noqa: E501
        """
        pass

    def test_find_companies(self):
        """Test case for find_companies

        Get User companies  # noqa: E501
        """
        pass

    def test_find_teams(self):
        """Test case for find_teams

        Get Teams  # noqa: E501
        """
        pass

    def test_get_acl_documents(self):
        """Test case for get_acl_documents

        Get Access Control List  # noqa: E501
        """
        pass

    def test_get_acl_folders(self):
        """Test case for get_acl_folders

        Get Access Control List  # noqa: E501
        """
        pass

    def test_get_assembly_definition_assemblies(self):
        """Test case for get_assembly_definition_assemblies

        Assembly Definition  # noqa: E501
        """
        pass

    def test_get_bend_table_parts(self):
        """Test case for get_bend_table_parts

        Get Sheet Metal Bend Table  # noqa: E501
        """
        pass

    def test_get_bill_of_materials_assemblies(self):
        """Test case for get_bill_of_materials_assemblies

        Get Bill of Materials  # noqa: E501
        """
        pass

    def test_get_body_details_part_studios(self):
        """Test case for get_body_details_part_studios

        Body Details  # noqa: E501
        """
        pass

    def test_get_body_details_parts(self):
        """Test case for get_body_details_parts

        Body Details  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_assemblies(self):
        """Test case for get_bounding_boxes_assemblies

        Bounding Boxes  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_for_sketch_part_studios(self):
        """Test case for get_bounding_boxes_for_sketch_part_studios

        Sketch Bounding Box  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_part_studios(self):
        """Test case for get_bounding_boxes_part_studios

        Bounding Box  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_parts(self):
        """Test case for get_bounding_boxes_parts

        Bounding Boxes  # noqa: E501
        """
        pass

    def test_get_client_plans_billing(self):
        """Test case for get_client_plans_billing

        Get billing plans for client.  # noqa: E501
        """
        pass

    def test_get_companies(self):
        """Test case for get_companies

        Get company  # noqa: E501
        """
        pass

    def test_get_company_release_workflow_release_management(self):
        """Test case for get_company_release_workflow_release_management

        release workflow details  # noqa: E501
        """
        pass

    def test_get_configuration_part_studios(self):
        """Test case for get_configuration_part_studios

        Get Configuration  # noqa: E501
        """
        pass

    def test_get_configured_element_thumbnail_with_size_thumbnails(self):
        """Test case for get_configured_element_thumbnail_with_size_thumbnails

        Get Configured Element Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_current_microversion_documents(self):
        """Test case for get_current_microversion_documents

        Get Current Document Microversion  # noqa: E501
        """
        pass

    def test_get_document_documents(self):
        """Test case for get_document_documents

        Get Document  # noqa: E501
        """
        pass

    def test_get_document_permission_set_documents(self):
        """Test case for get_document_permission_set_documents

        Get Document Permissions  # noqa: E501
        """
        pass

    def test_get_document_thumbnail_thumbnails(self):
        """Test case for get_document_thumbnail_thumbnails

        Get Document Thumbnail Info  # noqa: E501
        """
        pass

    def test_get_document_thumbnail_with_size_thumbnails(self):
        """Test case for get_document_thumbnail_with_size_thumbnails

        Get Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_documents_documents(self):
        """Test case for get_documents_documents

        Get Documents  # noqa: E501
        """
        pass

    def test_get_edges_part_studios(self):
        """Test case for get_edges_part_studios

        Tessellated Edges  # noqa: E501
        """
        pass

    def test_get_edges_parts(self):
        """Test case for get_edges_parts

        Tessellated Edges  # noqa: E501
        """
        pass

    def test_get_element_list_documents(self):
        """Test case for get_element_list_documents

        Element List  # noqa: E501
        """
        pass

    def test_get_element_metadata_elements(self):
        """Test case for get_element_metadata_elements

        Get Metadata  # noqa: E501
        """
        pass

    def test_get_element_thumbnail_thumbnails(self):
        """Test case for get_element_thumbnail_thumbnails

        Get Element Thumbnail Info  # noqa: E501
        """
        pass

    def test_get_element_thumbnail_with_size_thumbnails(self):
        """Test case for get_element_thumbnail_with_size_thumbnails

        Get Element Thumbnail With Size  # noqa: E501
        """
        pass

    def test_get_endpoints_endpoints(self):
        """Test case for get_endpoints_endpoints

        Get Endpoints  # noqa: E501
        """
        pass

    def test_get_faces_part_studios(self):
        """Test case for get_faces_part_studios

        Tessellated Faces  # noqa: E501
        """
        pass

    def test_get_faces_parts(self):
        """Test case for get_faces_parts

        Tessellated Faces  # noqa: E501
        """
        pass

    def test_get_feature_specs_assemblies(self):
        """Test case for get_feature_specs_assemblies

        Get Feature Specs  # noqa: E501
        """
        pass

    def test_get_feature_specs_part_studios(self):
        """Test case for get_feature_specs_part_studios

        Get Feature Specs  # noqa: E501
        """
        pass

    def test_get_feature_studio_contents_feature_studios(self):
        """Test case for get_feature_studio_contents_feature_studios

        Get Feature Studio Contents  # noqa: E501
        """
        pass

    def test_get_feature_studio_specs_feature_studios(self):
        """Test case for get_feature_studio_specs_feature_studios

        Get Feature Studio Specs  # noqa: E501
        """
        pass

    def test_get_features_assemblies(self):
        """Test case for get_features_assemblies

        Get Feature List  # noqa: E501
        """
        pass

    def test_get_features_part_studios(self):
        """Test case for get_features_part_studios

        Get Feature List  # noqa: E501
        """
        pass

    def test_get_history_by_workspace_app_elements(self):
        """Test case for get_history_by_workspace_app_elements

        Get History  # noqa: E501
        """
        pass

    def test_get_insertables_documents(self):
        """Test case for get_insertables_documents

        Insertable List for Document Version.  # noqa: E501
        """
        pass

    def test_get_mass_properties_part_studios(self):
        """Test case for get_mass_properties_part_studios

        Mass Properties  # noqa: E501
        """
        pass

    def test_get_mass_properties_parts(self):
        """Test case for get_mass_properties_parts

        Mass Properties  # noqa: E501
        """
        pass

    def test_get_metadata_metadata(self):
        """Test case for get_metadata_metadata

        Get Workspace / Version Metadata  # noqa: E501
        """
        pass

    def test_get_metadata_part_studios(self):
        """Test case for get_metadata_part_studios

        Part Metadata  # noqa: E501
        """
        pass

    def test_get_metadata_property_metadata(self):
        """Test case for get_metadata_property_metadata

        Get metadata property  # noqa: E501
        """
        pass

    def test_get_metadata_schema_by_id_metadata(self):
        """Test case for get_metadata_schema_by_id_metadata

        Get metadata schema by ID  # noqa: E501
        """
        pass

    def test_get_metadata_schema_metadata(self):
        """Test case for get_metadata_schema_metadata

        Get metadata schema by owner  # noqa: E501
        """
        pass

    def test_get_metadata_schema_properties_metadata(self):
        """Test case for get_metadata_schema_properties_metadata

        Get metadata properties  # noqa: E501
        """
        pass

    def test_get_named_views_assemblies(self):
        """Test case for get_named_views_assemblies

        Get Named Views  # noqa: E501
        """
        pass

    def test_get_named_views_part_studios(self):
        """Test case for get_named_views_part_studios

        Get Named Views  # noqa: E501
        """
        pass

    def test_get_or_create_bill_of_materials_element_assemblies(self):
        """Test case for get_or_create_bill_of_materials_element_assemblies

        Get or Create Bill of Materials Element  # noqa: E501
        """
        pass

    def test_get_part_list_metadata_metadata(self):
        """Test case for get_part_list_metadata_metadata

        Get Parts Metadata  # noqa: E501
        """
        pass

    def test_get_part_metadata_metadata(self):
        """Test case for get_part_metadata_metadata

        Get Part Metadata  # noqa: E501
        """
        pass

    def test_get_part_metadata_parts(self):
        """Test case for get_part_metadata_parts

        Get Metadata  # noqa: E501
        """
        pass

    def test_get_parts_in_partstudio_parts(self):
        """Test case for get_parts_in_partstudio_parts

        Get Parts In Part Studio  # noqa: E501
        """
        pass

    def test_get_parts_parts(self):
        """Test case for get_parts_parts

        Get Parts  # noqa: E501
        """
        pass

    def test_get_plan_purchases_accounts(self):
        """Test case for get_plan_purchases_accounts

        Get Plan Purchases  # noqa: E501
        """
        pass

    def test_get_purchases_accounts(self):
        """Test case for get_purchases_accounts

        Get User's Appstore Purchases  # noqa: E501
        """
        pass

    def test_get_release_package_release_management(self):
        """Test case for get_release_package_release_management

        Get Release Package by id  # noqa: E501
        """
        pass

    def test_get_revision_history_in_company_revisions(self):
        """Test case for get_revision_history_in_company_revisions

          # noqa: E501
        """
        pass

    def test_get_session_info_users(self):
        """Test case for get_session_info_users

        Get Session Info  # noqa: E501
        """
        pass

    def test_get_shaded_views_assemblies(self):
        """Test case for get_shaded_views_assemblies

        Shaded Views  # noqa: E501
        """
        pass

    def test_get_shaded_views_part_studios(self):
        """Test case for get_shaded_views_part_studios

        Shaded Views  # noqa: E501
        """
        pass

    def test_get_shaded_views_parts(self):
        """Test case for get_shaded_views_parts

        Shaded views  # noqa: E501
        """
        pass

    def test_get_sketch_info_part_studios(self):
        """Test case for get_sketch_info_part_studios

        Sketch Information  # noqa: E501
        """
        pass

    def test_get_standard_content_metadata_metadata(self):
        """Test case for get_standard_content_metadata_metadata

        Get Standard Content Part Metadata  # noqa: E501
        """
        pass

    def test_get_standard_content_part_metadata_parts(self):
        """Test case for get_standard_content_part_metadata_parts

        Get Standard Content Metadata  # noqa: E501
        """
        pass

    def test_get_sub_element_content_app_elements(self):
        """Test case for get_sub_element_content_app_elements

        Get Content  # noqa: E501
        """
        pass

    def test_get_sub_element_ids_app_elements(self):
        """Test case for get_sub_element_ids_app_elements

        Get Sub-element IDs  # noqa: E501
        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        Get Team  # noqa: E501
        """
        pass

    def test_get_tessellated_entities_part_studios(self):
        """Test case for get_tessellated_entities_part_studios

        Tessellated sketch entitites  # noqa: E501
        """
        pass

    def test_get_thumbnail_for_document_and_version_thumbnails(self):
        """Test case for get_thumbnail_for_document_and_version_thumbnails

        Get Thumbnail Info For Document Version  # noqa: E501
        """
        pass

    def test_get_thumbnail_for_document_thumbnails(self):
        """Test case for get_thumbnail_for_document_thumbnails

        Get Default Workspace Thumbnail Info  # noqa: E501
        """
        pass

    def test_get_translation_formats_assemblies(self):
        """Test case for get_translation_formats_assemblies

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_get_translation_formats_blob_elements(self):
        """Test case for get_translation_formats_blob_elements

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_get_translation_formats_drawings(self):
        """Test case for get_translation_formats_drawings

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_get_translation_formats_part_studios(self):
        """Test case for get_translation_formats_part_studios

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_get_translation_translations(self):
        """Test case for get_translation_translations

        Get Translation Status  # noqa: E501
        """
        pass

    def test_get_translations_translations(self):
        """Test case for get_translations_translations

        Get Translation Status for a document  # noqa: E501
        """
        pass

    def test_get_translator_formats_translations(self):
        """Test case for get_translator_formats_translations

        Get Translation Formats  # noqa: E501
        """
        pass

    def test_get_user_app_settings_applications(self):
        """Test case for get_user_app_settings_applications

        Get User Application Settings  # noqa: E501
        """
        pass

    def test_get_user_settings_current_logged_in_user_users(self):
        """Test case for get_user_settings_current_logged_in_user_users

        Get User Settings  # noqa: E501
        """
        pass

    def test_get_user_settings_users(self):
        """Test case for get_user_settings_users

        Get User Settings  # noqa: E501
        """
        pass

    def test_get_version_documents(self):
        """Test case for get_version_documents

        Get Version  # noqa: E501
        """
        pass

    def test_get_versions_documents(self):
        """Test case for get_versions_documents

        Get Versions  # noqa: E501
        """
        pass

    def test_get_webhook_webhooks(self):
        """Test case for get_webhook_webhooks

        Get Webhook  # noqa: E501
        """
        pass

    def test_get_workspaces_documents(self):
        """Test case for get_workspaces_documents

        Get Workspaces  # noqa: E501
        """
        pass

    def test_id_translations_part_studios(self):
        """Test case for id_translations_part_studios

        Id Translations  # noqa: E501
        """
        pass

    def test_insert_transformed_instances_assemblies(self):
        """Test case for insert_transformed_instances_assemblies

        Create and transform assembly instances  # noqa: E501
        """
        pass

    def test_move_elements_to_document_documents(self):
        """Test case for move_elements_to_document_documents

        Move Elements  # noqa: E501
        """
        pass

    def test_ping_webhook_webhooks(self):
        """Test case for ping_webhook_webhooks

        Ping Webhook  # noqa: E501
        """
        pass

    def test_resolve_reference_app_elements(self):
        """Test case for resolve_reference_app_elements

        Resolve Reference  # noqa: E501
        """
        pass

    def test_set_application_element_thumbnail_thumbnails(self):
        """Test case for set_application_element_thumbnail_thumbnails

        Set Application Element Thumbnail  # noqa: E501
        """
        pass

    def test_share_document_documents(self):
        """Test case for share_document_documents

        Share Document  # noqa: E501
        """
        pass

    def test_share_folder_folders(self):
        """Test case for share_folder_folders

        Share Folder  # noqa: E501
        """
        pass

    def test_start_transaction_app_elements(self):
        """Test case for start_transaction_app_elements

        Start Transaction  # noqa: E501
        """
        pass

    def test_test_version2_versions(self):
        """Test case for test_version2_versions

        Test Version 2  # noqa: E501
        """
        pass

    def test_transform_occurrences_assemblies(self):
        """Test case for transform_occurrences_assemblies

        Transform assembly occurrences  # noqa: E501
        """
        pass

    def test_un_share_documents(self):
        """Test case for un_share_documents

        Unshare Document  # noqa: E501
        """
        pass

    def test_un_share_folders(self):
        """Test case for un_share_folders

        Unshare Folder  # noqa: E501
        """
        pass

    def test_unregister_webhook_webhooks(self):
        """Test case for unregister_webhook_webhooks

        Unregister Webhook  # noqa: E501
        """
        pass

    def test_update_app_settings_applications(self):
        """Test case for update_app_settings_applications

        Update Application Settings  # noqa: E501
        """
        pass

    def test_update_configuration_part_studios(self):
        """Test case for update_configuration_part_studios

        Update Configuration  # noqa: E501
        """
        pass

    def test_update_document_attributes_documents(self):
        """Test case for update_document_attributes_documents

        Update Document Attributes.  # noqa: E501
        """
        pass

    def test_update_element_app_elements(self):
        """Test case for update_element_app_elements

        Update Element  # noqa: E501
        """
        pass

    def test_update_element_metadata_elements(self):
        """Test case for update_element_metadata_elements

        Update Element Metadata  # noqa: E501
        """
        pass

    def test_update_external_references_to_latest_documents_documents(self):
        """Test case for update_external_references_to_latest_documents_documents

        Update External References to Latest  # noqa: E501
        """
        pass

    def test_update_feature_assemblies(self):
        """Test case for update_feature_assemblies

        Update Feature  # noqa: E501
        """
        pass

    def test_update_feature_part_studios(self):
        """Test case for update_feature_part_studios

        Update Feature  # noqa: E501
        """
        pass

    def test_update_feature_studio_contents_feature_studios(self):
        """Test case for update_feature_studio_contents_feature_studios

        Update Feature Studio contents  # noqa: E501
        """
        pass

    def test_update_features_part_studios(self):
        """Test case for update_features_part_studios

        Update Features  # noqa: E501
        """
        pass

    def test_update_metadata_metadata(self):
        """Test case for update_metadata_metadata

        Update Metadata  # noqa: E501
        """
        pass

    def test_update_part_metadata_parts(self):
        """Test case for update_part_metadata_parts

        Update Metadata  # noqa: E501
        """
        pass

    def test_update_reference_app_elements(self):
        """Test case for update_reference_app_elements

        Update Reference  # noqa: E501
        """
        pass

    def test_update_release_package_release_management(self):
        """Test case for update_release_package_release_management

        Update Release Package  # noqa: E501
        """
        pass

    def test_update_rollback_part_studios(self):
        """Test case for update_rollback_part_studios

        Update Feature Rollback  # noqa: E501
        """
        pass

    def test_update_standard_content_metadata_metadata(self):
        """Test case for update_standard_content_metadata_metadata

        Update Standard Content Part Metadata  # noqa: E501
        """
        pass

    def test_update_standard_content_part_metadata_parts(self):
        """Test case for update_standard_content_part_metadata_parts

        Update Standard Content Metadata  # noqa: E501
        """
        pass

    def test_update_webhook_webhooks(self):
        """Test case for update_webhook_webhooks

        Update Webhook  # noqa: E501
        """
        pass

    def test_upload_file_create_element_blob_elements(self):
        """Test case for upload_file_create_element_blob_elements

        Upload File to New Blob Element  # noqa: E501
        """
        pass

    def test_upload_file_update_element_blob_elements(self):
        """Test case for upload_file_update_element_blob_elements

        Update Blob Element  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
