# coding: utf-8

"""
    Onshape API

    Onshape API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ekeller@onshape.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parts_api import PartsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPartsApi(unittest.TestCase):
    """PartsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parts_api.PartsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_update_part_metadata_parts(self):
        """Test case for batch_update_part_metadata_parts

        Update Part metadata  # noqa: E501
        """
        pass

    def test_export_parasolid_parts(self):
        """Test case for export_parasolid_parts

        Export Part to Parasolid  # noqa: E501
        """
        pass

    def test_export_stl_parts(self):
        """Test case for export_stl_parts

        Export Part to STL  # noqa: E501
        """
        pass

    def test_get_bend_table_parts(self):
        """Test case for get_bend_table_parts

        Get Sheet Metal Bend Table  # noqa: E501
        """
        pass

    def test_get_body_details_parts(self):
        """Test case for get_body_details_parts

        Body Details  # noqa: E501
        """
        pass

    def test_get_bounding_boxes_parts(self):
        """Test case for get_bounding_boxes_parts

        Bounding Boxes  # noqa: E501
        """
        pass

    def test_get_edges_parts(self):
        """Test case for get_edges_parts

        Tessellated Edges  # noqa: E501
        """
        pass

    def test_get_faces_parts(self):
        """Test case for get_faces_parts

        Tessellated Faces  # noqa: E501
        """
        pass

    def test_get_mass_properties_parts(self):
        """Test case for get_mass_properties_parts

        Mass Properties  # noqa: E501
        """
        pass

    def test_get_part_metadata_parts(self):
        """Test case for get_part_metadata_parts

        Get Metadata  # noqa: E501
        """
        pass

    def test_get_parts_in_partstudio_parts(self):
        """Test case for get_parts_in_partstudio_parts

        Get Parts In Part Studio  # noqa: E501
        """
        pass

    def test_get_parts_parts(self):
        """Test case for get_parts_parts

        Get Parts  # noqa: E501
        """
        pass

    def test_get_shaded_views_parts(self):
        """Test case for get_shaded_views_parts

        Shaded views  # noqa: E501
        """
        pass

    def test_get_standard_content_part_metadata_parts(self):
        """Test case for get_standard_content_part_metadata_parts

        Get Standard Content Metadata  # noqa: E501
        """
        pass

    def test_update_part_metadata_parts(self):
        """Test case for update_part_metadata_parts

        Update Metadata  # noqa: E501
        """
        pass

    def test_update_standard_content_part_metadata_parts(self):
        """Test case for update_standard_content_part_metadata_parts

        Update Standard Content Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
